# Generated by Django 4.0.1 on 2022-02-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryID',
            field=models.ForeignKey(choices=[('national', 'National'), ('international', 'International'), ('club', 'Club'), ('player', 'Player')], default='national', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Home.category'),
        ),
    ]
