# Generated by Django 4.0.1 on 2022-02-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='name',
        ),
    ]
