# Generated by Django 4.0.1 on 2022-03-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
