# Generated by Django 4.0.1 on 2022-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_category_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryID',
            new_name='category',
        ),
    ]
