# Generated by Django 4.0.1 on 2022-02-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_variation_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
