# Generated by Django 4.0.1 on 2022-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_customize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='number',
            field=models.IntegerField(),
        ),
    ]
