# Generated by Django 4.0.1 on 2022-02-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='national', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Home.category'),
        ),
    ]
