# Generated by Django 4.0.1 on 2022-04-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_currencystate_exchangerate'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordered',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemOrder', to='Home.product'),
        ),
    ]
