# Generated by Django 4.0.1 on 2022-04-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_itemordered_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordered',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='Order.order'),
        ),
    ]
