# Generated by Django 4.0.1 on 2022-04-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_currencystate_exchangerate'),
        ('Order', '0003_alter_itemordered_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordered',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order'),
        ),
        migrations.AlterField(
            model_name='itemordered',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemOrder', to='Home.product'),
        ),
    ]
