# Generated by Django 4.0.1 on 2022-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
